### ISSUE TITLE
♻️ [Refactoring] 카드 상태 String -> 카드 태그를 db에 저장후 ManyToMany관계 구현

### ISSUE THREAD

**Issue by LeeChangHyeong** [Oe-In-DevelopTeam/TaskNavigator#36]
**♻️ Issue : Refactoring**
카드 상태를 String에서 카드 태그를 db에 저장하도록 리팩토링

**Description**
카드 상태를 원래 사용자 마음대로 String으로 정할 수 있었는데 db에 태그들을 저장하여 제공하여 사용하게 구현

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 카드와 태그를 매치할 테이블 생성
- [x] 서치 속도를 위해 복합키 설정
- [x] 카드, 태그를 카드 태그 매치 테이블에 OneToMany로 연결
