### ISSUE TITLE
♻️ [Refactoring] 프론트 페이지 연동

### ISSUE THREAD

**Issue by chamcham0707** [Oe-In-DevelopTeam/TaskNavigator#56]
**♻️ Issue : Refactoring**
프론트 페이지를 연동합니다.

**Description**
프론트의 html 파일을 백엔드와 붙입니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 회원가입 페이지 붙이기
- [x] 메인 페이지 붙이기
- [x] 보드 만들기 페이지 붙이기
- [x] 카드 생성 페이지 붙이기
- [x] 카드 상세 페이지 붙이기

**Reference(Optional)**
