### ISSUE TITLE
♻️ [Refactoring] 유저 기능 

### ISSUE THREAD

**Issue by nenney** [Oe-In-DevelopTeam/TaskNavigator#59]
**♻️ Issue : Refactoring**
User 관련하여 fix 및 refactoring 합니다.

**Description**
리팩토링에 대한 설명을 작성해주세요
- UserRoleMatches 테이블에 데이터 들어가지 않는 오류 수정
- ErrorCode 세분화
- getUser 메서드 삭제 후, getPrincipal 을 UserDetailsImpl 에서 바로 주입
- FetchType: EAGER -> fetchjoin 으로 수정해서 해결
- "MANAGER" 이미 있으면 예외 처리
- 비밀번호 재사용 방지 기능 삭제

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] UserRoleMatches 테이블 오류 수정
- [x] ErrorCode 세분화
- [x] getUser 메서드 삭제 후, logout 수정
- [x] FetchType: EAGER -> fetchjoin 으로 수정해서 해결
- [x] "MANAGER" 이미 있으면 예외 처리
- [x] 비밀번호 재사용 방지 기능 삭제

**Reference(Optional)**
