### ISSUE TITLE
🌟 [Feature] 댓글 조회 기능

### ISSUE THREAD

**Issue by LeeChangHyeong** [Oe-In-DevelopTeam/TaskNavigator#72]
**🌟 Issue : Feature**
댓글 조회 기능

**Description**
카드 id 기능을 구현하여 댓글 조회 기능을 구현

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [ ] 해당 보드에 권한이 있는지 확인하는 로직 구현
- [ ] 댓글 조회 api 구현
- [ ] 댓글 조회 로직 구현
